pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t flask-app DevOps-Project-Two-Tier-Flask-App'
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                sh '''
                  cd DevOps-Project-Two-Tier-Flask-App
                  docker compose down || true
                  docker compose up -d
                '''
            }
        }
    }
}
