pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/aksnki/DevOps-Project-Two-Tier-Flask-App.git'
            }
        }

        stage('Build Image') {
            steps {
                sh '''
                cd DevOps-Project-Two-Tier-Flask-App
                docker build -t flask-app:latest .
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd DevOps-Project-Two-Tier-Flask-App
                docker compose up -d --no-build
                '''
            }
        }
    }
}
