pipeline{
    agent any
    stages{
        stage('Clone repo'){
            steps{
                git branch: 'main', url: 'https://github.com/aksnki/DevOps-Project-Two-Tier-Flask-App.git'
            }
        }
        stage('Build image') {
           steps {
                 sh 'docker build -t flask-app DevOps-Project-Two-Tier-Flask-App'
            }
        }
        stage('Deploy with docker compose'){
            steps{
               sh '''
               cd DevOps-Project-Two-Tier-Flask-App
               docker compose down || true
               docker compose up -d
                  '''
            }
        }
    }
}
